### PR TITLE
ISS-168 # multipart/form-data support without file

### LINKED ISSUE #168: Cannot send multipart/form-data without a file
`multipart/form-data` is used to send **key-value** pairs in the body of the request. The key should be string and ***value can be either string or it can be a file***. It is not mandatory to provide the file to send a `multipart/form-data` request. 

In the current implementation, if `multipart/form-data` does not contain any file then `null pointer exception` is thrown. There should be a `null check and empty check` for smooth functioning of the BasicHttpClient. 

There is a work around to overcome this issue untill next release by overriding the below method in your `HttpClient`

```java
        @Override
	public RequestBuilder createFileUploadRequestBuilder(String httpUrl, String methodName, String reqBodyAsString) throws IOException {
        Map<String, Object> fileFieldNameValueMap = FileUploadUtils.getFileFieldNameValue(reqBodyAsString);

        List<String> fileFieldsList = (List<String>) fileFieldNameValueMap.get(FILES_FIELD);

        MultipartEntityBuilder multipartEntityBuilder = MultipartEntityBuilder.create();

        // Hot fix for the issue
        if(fileFieldsList != null && !fileFieldsList.isEmpty()) {
        FileUploadUtils.buildAllFilesToUpload(fileFieldsList, multipartEntityBuilder);
        }
        FileUploadUtils.buildOtherRequestParams(fileFieldNameValueMap, multipartEntityBuilder);

        FileUploadUtils.buildMultiPartBoundary(fileFieldNameValueMap, multipartEntityBuilder);

        return FileUploadUtils.createUploadRequestBuilder(httpUrl, methodName, multipartEntityBuilder);
    }
```

### PR DESCRIPTION
**Pull request by santhoshTpixler**
Fixes #168 , also added adequate tests to verify the fix. I am open for suggestions.

### CODE REVIEW

File: src/main/java/org/jsmart/zerocode/core/httpclient/BasicHttpClient.java [hunk 1]
```diff
@@ -344,7 +344,14 @@ public RequestBuilder createFileUploadRequestBuilder(String httpUrl, String meth
 
         MultipartEntityBuilder multipartEntityBuilder = MultipartEntityBuilder.create();
 
-        buildAllFilesToUpload(fileFieldsList, multipartEntityBuilder);
+        /*
+	 * Allow fileFieldsList to be null.
+	 * fileFieldsList can be null if multipart/form-data is sent without any files
+	 * Refer Issue #168 - Raised and fixed by santhoshTpixler
+	 */
+        if(fileFieldsList != null) {
```
Comment (authorjapps) [inline src/main/java/org/jsmart/zerocode/core/httpclient/BasicHttpClient.java]: 👍

**Comment by authorjapps** [comment]
PR approved.
Will merge it soon and this will be available in the release along with the feature #167 . 👍
