### PR TITLE
ISS-241 # Display assumed payload and assertions on step error

### LINKED ISSUE #241: Console Report missing assertions section for failed step
Hello Folks, 
It seems like there is a minor bug introduced while printing the correlated test results/assertions.

### Reproduction
- Fail a test step in the scenario/journey
- See the console and look for the failed step
- After request/response section we used to see the `assertions` section.
  - > it used to be handy
- Now we don't see that. But we see all mismatches as usual(no changes)
- FYI- We see this `assertions` section for the passed steps.
Hence looks like a minor one.

Could you please check?

### PR DESCRIPTION
**Pull request by jneate**
PR to fix #241 - Basic Unit test added to verify assertions section is updated on step failure

The implemented code doesn't alter the "happy" path, behaviour is unchanged and only the payload is displayed.

Images below show example outputs in Console, JSON and HTML report.
image

image

image

image

### CODE REVIEW

File: core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java [hunk 1]
```diff
@@ -242,6 +242,11 @@ public synchronized boolean runScenario(ScenarioSpec scenario, RunNotifier notif
 
                         if (!failureResults.isEmpty()) {
                             StringBuilder builder = new StringBuilder();
+
```
Comment (authorjapps) [inline core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java]: 👍

File: core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java [hunk 2]
```diff
@@ -242,6 +242,11 @@ public synchronized boolean runScenario(ScenarioSpec scenario, RunNotifier notif
 
                         if (!failureResults.isEmpty()) {
                             StringBuilder builder = new StringBuilder();
+                            
+                            // JNEATE 21-05-2019 - Print expected Payload along with assertion errors
+                            builder.append("Assumed Payload: \n" + prettyPrintJson(resolvedAssertionJson) + "\n");
```
Comment (authorjapps) [inline core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java]: 👍

File: core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunner_FailedAssertions.java [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+import org.jsmart.zerocode.core.di.provider.ObjectMapperProvider;
+import org.jsmart.zerocode.core.domain.reports.ZeroCodeReport;
+import org.jsmart.zerocode.core.runner.e2e.FailSimpleAssertionInMultiStep;
+import org.junit.Test;
+import org.junit.runner.JUnitCore;
+import org.junit.runner.Result;
+
+import com.fasterxml.jackson.databind.ObjectMapper;
+
+public class ZeroCodeMultiStepsScenarioRunner_FailedAssertions {
```
Comment (authorjapps) [inline core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunner_FailedAssertions.java]: Thanks for the test coverage.

Can you pls rename the class to (ending with *...Test*.java)?
> ZeroCodeMultiStepsScenarioRunnerFailedAssertionsTest

Otherwise it may not be the picked by CI build :-).

Comment (jneate) [reply core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunner_FailedAssertions.java]: My bad.. 👍

File: core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java (hunk 2 above)
Comment (jneate) [reply core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java]: 👍
